USE ecommerce_product;
-- ============================================================
-- product 域：种子数据
-- ============================================================

INSERT INTO product_category (parent_id, name, sort_order) VALUES
(NULL, '数码办公', 1),
(1, '输入设备', 1),
(NULL, '影音与会议', 2),
(3, '音视频', 1),
(NULL, '扩展与连接', 3),
(5, '存储网络', 1),
(NULL, '桌面效率', 4),
(7, '桌面办公', 1);

INSERT INTO product (category_id, name, price, stock, sales, is_on_sale, image_url, detail_html, params_text) VALUES
(2, 'Koolertron One Handed Programmable Mechanical Keyboard with OEM Gateron Red Switch,All 48 Programmable Keys Tools...', 85.99, 31, 8, 1, '/catalog/B076LRJ528.webp', 'Read more Macro Keyboard Specifications: All 48 keys are programmable, 8 Macro Keys,No backlit Key number: 48 Keyboard switch: OEM Gateron Red Keystroke force: 45±15cN Interface: 2 MINI USB Interfaces, USB2.1M detachable USB cable Rating: DC 5V, &lt;

INSERT INTO product_spec (product_id, spec_name, spec_value) VALUES
(1, '品牌', 'Koolertron'),
(1, '型号', 'AE-SMKD7'),
(1, '来源', '公开商品样本'),
(2, '品牌', 'Razer'),
(2, '型号', '‎RZ01-03210300-R3M1'),
(2, '来源', '公开商品样本'),
(3, '品牌', 'R-Go Tools'),
(3, '型号', '‎RGOSP-USWIBL'),
(3, '来源', '公开商品样本'),
(4, '品牌', 'Allsop'),
(4, '型号', 'ASP30203'),
(4, '来源', '公开商品样本'),
(5, '品牌', 'YSAGi'),
(5, '型号', 'v40'),
(5, '来源', '公开商品样本'),
(6, '品牌', 'EMINTA'),
(6, '型号', 'E00BU'),
(6, '来源', '公开商品样本'),
(7, '品牌', 'Aothia'),
(7, '来源', '公开商品样本'),
(8, '品牌', 'EKSA'),
(8, '型号', 'H1'),
(8, '来源', '公开商品样本'),
(9, '品牌', 'MusiBady'),
(9, '型号', 'M77 speaker'),
(9, '来源', '公开商品样本'),
(10, '品牌', 'JOLIKE'),
(10, '型号', 'M4s-32GB'),
(10, '来源', '公开商品样本'),
(11, '品牌', 'Sony'),
(11, '型号', 'SRSXP500'),
(11, '来源', '公开商品样本'),
(12, '品牌', 'Razer'),
(12, '型号', 'RZ04-02051000-R3M1'),
(12, '来源', '公开商品样本'),
(13, '品牌', 'Coleman'),
(13, '型号', 'CBT11-R'),
(13, '来源', '公开商品样本'),
(14, '品牌', 'IOGEAR'),
(14, '型号', 'GCS62HU'),
(14, '来源', '公开商品样本'),
(15, '品牌', 'GearIT'),
(15, '型号', '‏ ‎ GI-PRO-HD2-6.6F-2PK'),
(15, '来源', '公开商品样本'),
(16, '品牌', 'Seagate'),
(16, '型号', 'STKP18000400'),
(16, '来源', '公开商品样本'),
(17, '品牌', 'GearIT'),
(17, '型号', '‏ ‎ 6CAT6E-ORANGE-24PK'),
(17, '来源', '公开商品样本'),
(18, '品牌', 'Linksys'),
(18, '型号', 'MR20EC-AMZ'),
(18, '来源', '公开商品样本'),
(19, '品牌', 'Seagate'),
(19, '型号', '‎STJW500401'),
(19, '来源', '公开商品样本'),
(20, '品牌', 'MAIWO'),
(20, '型号', 'M.2 SATA/NVME'),
(20, '来源', '公开商品样本'),
(21, '品牌', 'Swingline'),
(21, '型号', 'S7074769'),
(21, '来源', '公开商品样本'),
(22, '品牌', 'Rotring'),
(22, '型号', '2114263'),
(22, '来源', '公开商品样本'),
(23, '品牌', 'Dunwell'),
(23, '型号', 'DISPLTR12'),
(23, '来源', '公开商品样本'),
(24, '品牌', 'Xerox'),
(24, '型号', '‎006R01220'),
(24, '来源', '公开商品样本'),
(25, '品牌', 'Safco'),
(25, '型号', '3257BL'),
(25, '来源', '公开商品样本'),
(26, '品牌', 'AVERY'),
(26, '型号', '‎05741'),
(26, '来源', '公开商品样本'),
(27, '品牌', 'O2COOL'),
(27, '来源', '公开商品样本'),
(28, '品牌', 'Drawealth'),
(28, '型号', '‎T0085'),
(28, '来源', '公开商品样本'),
(29, '品牌', 'Simple Designs'),
(29, '型号', 'LT3039-PRP'),
(29, '来源', '公开商品样本'),
(30, '品牌', 'Brother'),
(30, '型号', '‎TN620'),
(30, '来源', '公开商品样本');

INSERT INTO product_review (user_id, product_id, rating, content, image_url, created_at) VALUES
(1, 1, 4, 'I was worried about this one. I''ve been spurned before. Overall I''m pretty happy with it, though.I''ve been PC gaming since middle school, but I broke my right arm when I was in high school. I can use a mouse in my right hand fine for day to day stuff but between the scar tissue and slight nerve pinching that causes it to be uncomfortable, really uncomfortable for gaming. For whatever reason using a keyboard in my right is fine though (I guess because my hand rests on it...', '', NOW()),
(1, 2, 5, 'Although I''ve never cared for the aesthetics or branding (it''s very tryhard and aimed at teenagers) in of Razer the overall build quality, ergonomics, and responsiveness of the mouse overcome any reservations.This is a wired mouse but unlike traditional hard rubber coated mouse cables this one is wrapped in a soft but sturdy woven material. It makes it so it doesn''t noticably resist as traditional mouse cables would which allows for smooth operation and makes for easy...', '', NOW()),
(1, 3, 3, 'Due to RSI, split keyboards are all I can use, and I''ve owned or still own well over a dozen, from Kinesis to Ergodox to homebuilt to Microsoft to you name it. I was looking for a thin split keyboard to make a portable ergonomic rig for travel.This keyboard fits the bill as it is very slim. In spite of the thinness, the key travel is significant and feels very good. There''s no wobble in the keys. If you''re familiar with Dell XPS, Macbook Pro (2015 and 2018), and modern...', '', NOW()),
(1, 4, 5, 'I tried other mouse pads, but nothing compares to this one!', '', NOW()),
(1, 5, 5, 'I don’t have a desk in my home, so I often do work on my dining room table. The worrisome part is that my dining room table is wood and I don’t want to scratch it or damage it any further than what was done during Covid. Then one day I stumbled onto this product. I fell in love with it. I can keep my water cup on top and not have to worry about water damage on the wood. I can have my laptop and mouse on it without having to worry about scratching my table. I can even have...', '', NOW()),
(1, 6, 5, 'As advertised, great price excellent buy', '', NOW()),
(1, 7, 5, 'I have a glass dining table and needed something to place my laptop on to prevent scratching of my table, and this is perfect. The size allows for my laptop and a mousepad/mouse and a drink with plenty of room. They wipe clean easily. The underside is cork. I love the color. I am very happy with the price, quality and size.', '', NOW()),
(1, 8, 4, 'The Bluetooth headset that I tested is a good product overall, but I must say it is not the best for driving. When I used it inside an office, people told me that it sounded great and had no issues. I even tested it with background noise from a TV, and it successfully canceled out the noise. However, the real problem arose when I took it on the road with the window down. The headset completely lost signal or people would say it sounded like I was underwater.I believe it...', '', NOW()),
(1, 9, 4, 'I recently bought the MusiBaby M77 Bluetooth Speaker and let me tell you, I used it at a pool party and it was a hit! The sound quality is fantastic. It fills the room (or backyard in my case) with strong, clear music. Bass? Deep and rich. Highs and mids? Crystal clear. I clipped it on my bag and had my tunes with me all the time. Battery life? Lasted all day, no sweat. One more cool thing - you can buy two and pair them for even more amazing sound. It feels like you''re...', '', NOW()),
(1, 10, 4, 'I originally gave this player 5 stars. Now I''m not sure where I stand on it. When I first got it last week, all was well. Today I plugged it into the USB port on my laptop and my laptop doesn''t even see that it''s plugged into the USB port. There''s no hope of interacting with this player to drop files into it from my laptop.I clicked on "Help" here on the Amazon page for this product and the first thing I found is "Why doesn''t my laptop see this player." -- Are you kidding...', '', NOW()),
(1, 11, 5, 'We have owned various speakers. Used lots. Listened to even more- softball games, camping, block parties, etc.These Sonys, for the price of a set are an amazing deal. No distortion. Great bass. Clean sounds. All the highs and lows you''d expect from a high end. And a great price.Do they have wheels, or a stand? No. Do they have great quality? Yes. Is it worth the trade off? Heck yes.', '', NOW()),
(1, 12, 4, 'I''m not much of a tech person so this won''t be a specs review. All I know is that I can hear a lot more going on in games than I can with some of the other Kraken models we''ve previously bought and that I can''t hear anything outside of the headphones unless I have it sitting slightly off of my ear 😅 I don''t dominately use these as they were a gift for my husband who plays games regularly. He said he really likes that it has a USB input to his computer rather than an aux...', '', NOW()),
(1, 13, 4, 'quick ship! good item quality :)', '', NOW()),
(1, 14, 4, 'THE GCS1942 ($433) IS THE ONE TO GET IF YOU HAVE DUAL 4K MONITORS!I recently upgraded my Win10 PC to a pair of LG 32" 4K monitors, which have DisplayPort inputs, and this $433 (OUCH!) IOGear GCS1942 DisplayPort KVM. My previous setup was a pair of 27" WQHD monitors with DVI-D inputs, and used an older IOGear DIV-D KVM which is also a dual-view KVM. I can then run two computers with dual monitors.So, I tried FOUR other KVM''s, and had issues all around. Issues like the...', '', NOW()),
(1, 15, 5, 'The .75 feet cord is sturdy. The way the connectors are wired is that when you stretch out the wire, one connector is "up" and one is "down." The wide part is up on one side and dow at the other end of the cable. This orientation works great if you are stacking components with both HDMI sockets oriented the same way, but my two components are side by side. A 1.5 ft. cable from another company did not survive the 180 degree twist. This shorter cable did survive.I am trying...', '', NOW()),
(1, 16, 5, 'The Seagate Portable 5TB External Hard Drive has become an indispensable companion for my digital storage needs, offering unmatched reliability, versatility, and convenience across multiple platforms. Whether I''m backing up important files, expanding storage capacity, or enhancing gaming experiences on my PC, Mac, PS4, or Xbox, this external hard drive consistently delivers exceptional performance and peace of mind.The first aspect that immediately impressed me about the...', '', NOW()),
(1, 17, 5, 'I work for an internet company. We are not huge but we are growing, 8-10 states last I checked. I found these cables and showed my boss. He agreed it was a great deal! By the time we buy cable, connectors, and pay a tech, it will cost way more than these cables. We did the math and it was almost a dollar for 2 RJ45s plus the cable (that depends on the footage) and then a tech to build and test. These also save a lot of time since they are pre-cut to the lengths we need for...', '', NOW()),
(1, 18, 4, 'Very easy to set up. Works great. Gave support 5 stars because of the help with my old router. Haven''t had to call tech support for the new one.', '', NOW()),
(1, 19, 5, 'bought this due to review comparing it to other drives by same manufacturerHowever still find it unbearably slowNow honestly, moving gigabites in volume is a lot of bits to move, so ???? .... but it clearly is usable as ''back up storrage'' only and NOT for ''live use'' of anything beyond looking at a small sized jpg.I am not unhappy, if it holds up as Back up storrage, but will need to find additional solutionsThis is great! Copies quickly, a one MB folder was completely...', '', NOW()),
(1, 20, 4, 'I used this for cloning my 256 GB stock SSD drive to a new 2 TB SSD for my Steam Deck. The enclosure got incredibly hot. Do not touch it til it cools down. I already expected it to get hot so it was not a surprise, because lots of data being transferred and no fan. It did the job excellently. Now it''s the home of my old Stock drive and I needed to reclone the stock image due to my own mistake, and it was fast. I can''t vouch for the longevity of the device and only for a...', '', NOW()),
(1, 21, 5, 'It’s a classic. Durable', '', NOW()),
(1, 22, 4, 'The pen in all it''s glory is amazing. Smooth, properly weighted for my liking. The only ting that I did not like is that I got delivered a pen with black ink, when the description clearly states blue ink. Couldn''t even find an option to return and request for refund.', '', NOW()),
(1, 23, 5, 'Very nice folder for what I need it for. I use them as substitute teacher folders for their assignments. The only issue I had was putting in the cover on the front. I used regular paper and it''s a bit difficult to slide in;

INSERT INTO product_spec (product_id, spec_name, spec_value) VALUES
(7, '型号', 'Aothia-Cork'),
(27, '型号', 'NPL10CPG');

INSERT INTO product_favorite (user_id, product_id) VALUES
(1, 11),
(1, 13);
