SET NAMES utf8mb4;
SET character_set_client = utf8mb4;
SET character_set_connection = utf8mb4;
SET character_set_results = utf8mb4;

USE ecommerce_product;
-- ============================================================
-- product 域：DummyJSON 商品主种子（30 个课堂演示商品）
-- 说明：原 Amazon 商品样本已改为历史备份，当前演示默认展示 DummyJSON 商品。
-- ============================================================

DELETE FROM product_favorite;
DELETE FROM product_review;
DELETE FROM product_spec;
DELETE FROM product_image;
DELETE FROM product_sku;
DELETE FROM product;
DELETE FROM product_category;
ALTER TABLE product AUTO_INCREMENT = 1;
ALTER TABLE product_category AUTO_INCREMENT = 1;
ALTER TABLE product_sku AUTO_INCREMENT = 1;
ALTER TABLE product_image AUTO_INCREMENT = 1;
ALTER TABLE product_spec AUTO_INCREMENT = 1;
ALTER TABLE product_review AUTO_INCREMENT = 1;

INSERT INTO product_category (id, parent_id, name, sort_order) VALUES
(1, NULL, '美妆个护', 1),
(2, NULL, '家居生活', 2),
(3, NULL, '全球精选', 3),
(11, 1, '美妆彩妆', 1),
(12, 1, '香水香氛', 2),
(13, 2, '家具软装', 3),
(14, 3, 'groceries', 4);

INSERT INTO product (id, category_id, name, subtitle, price, original_price, stock, sales, is_on_sale, image_url, detail_html, params_text) VALUES
(1, 11, 'Essence Mascara Lash Princess', 'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.', 9.99, 11.16, 99, 64, 1, 'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp', '<p>The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.</p><p>Brand: Essence</p><p>Rating: 2.56/5</p><p>Tags: beauty, mascara</p>', '品牌:Essence;分类:beauty;SKU:BEA-ESS-ESS-001;评分:2.56/5;折扣:10.48%;保修:1 week warranty;配送:Ships in 3-5 business days;来源:DummyJSON products'),
(2, 11, 'Eyeshadow Palette with Mirror', 'The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it''s convenient for on-the-go makeup application.', 19.99, 24.43, 34, 81, 1, 'https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/1.webp', '<p>The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it''s convenient for on-the-go makeup application.</p><p>Brand: Glamour Beauty</p><p>Rating: 2.86/5</p><p>Tags: beauty, eyeshadow</p>', '品牌:Glamour Beauty;分类:beauty;SKU:BEA-GLA-EYE-002;评分:2.86/5;折扣:18.19%;保修:1 year warranty;配送:Ships in 2 weeks;来源:DummyJSON products'),
(3, 11, 'Powder Canister', 'The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.', 14.99, 16.63, 89, 98, 1, 'https://cdn.dummyjson.com/product-images/beauty/powder-canister/1.webp', '<p>The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.</p><p>Brand: Velvet Touch</p><p>Rating: 4.64/5</p><p>Tags: beauty, face powder</p>', '品牌:Velvet Touch;分类:beauty;SKU:BEA-VEL-POW-003;评分:4.64/5;折扣:9.84%;保修:3 months warranty;配送:Ships in 1-2 business days;来源:DummyJSON products'),
(4, 11, 'Red Lipstick', 'The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.', 12.99, 14.79, 91, 115, 1, 'https://cdn.dummyjson.com/product-images/beauty/red-lipstick/1.webp', '<p>The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.</p><p>Brand: Chic Cosmetics</p><p>Rating: 4.36/5</p><p>Tags: beauty, lipstick</p>', '品牌:Chic Cosmetics;分类:beauty;SKU:BEA-CHI-LIP-004;评分:4.36/5;折扣:12.16%;保修:3 year warranty;配送:Ships in 1 week;来源:DummyJSON products'),
(5, 11, 'Red Nail Polish', 'The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.', 8.99, 10.15, 79, 72, 1, 'https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/1.webp', '<p>The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.</p><p>Brand: Nail Couture</p><p>Rating: 4.32/5</p><p>Tags: beauty, nail polish</p>', '品牌:Nail Couture;分类:beauty;SKU:BEA-NAI-NAI-005;评分:4.32/5;折扣:11.44%;保修:1 month warranty;配送:Ships overnight;来源:DummyJSON products'),
(6, 12, 'Calvin Klein CK One', 'CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It''s a versatile fragrance suitable for everyday wear.', 49.99, 50.95, 29, 89, 1, 'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/1.webp', '<p>CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It''s a versatile fragrance suitable for everyday wear.</p><p>Brand: Calvin Klein</p><p>Rating: 4.37/5</p><p>Tags: fragrances, perfumes</p>', '品牌:Calvin Klein;分类:fragrances;SKU:FRA-CAL-CAL-006;评分:4.37/5;折扣:1.89%;保修:1 week warranty;配送:Ships overnight;来源:DummyJSON products'),
(7, 12, 'Chanel Coco Noir Eau De', 'Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.', 129.99, 155.70, 58, 106, 1, 'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/1.webp', '<p>Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.</p><p>Brand: Chanel</p><p>Rating: 4.26/5</p><p>Tags: fragrances, perfumes</p>', '品牌:Chanel;分类:fragrances;SKU:FRA-CHA-CHA-007;评分:4.26/5;折扣:16.51%;保修:3 year warranty;配送:Ships overnight;来源:DummyJSON products'),
(8, 12, 'Dior J''adore', 'J''adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.', 89.99, 105.52, 98, 123, 1, 'https://cdn.dummyjson.com/product-images/fragrances/dior-j''adore/1.webp', '<p>J''adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.</p><p>Brand: Dior</p><p>Rating: 3.8/5</p><p>Tags: fragrances, perfumes</p>', '品牌:Dior;分类:fragrances;SKU:FRA-DIO-DIO-008;评分:3.8/5;折扣:14.72%;保修:1 week warranty;配送:Ships in 2 weeks;来源:DummyJSON products'),
(9, 12, 'Dolce Shine Eau de', 'Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It''s a joyful and youthful scent.', 69.99, 70.43, 4, 80, 1, 'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/1.webp', '<p>Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It''s a joyful and youthful scent.</p><p>Brand: Dolce & Gabbana</p><p>Rating: 3.96/5</p><p>Tags: fragrances, perfumes</p>', '品牌:Dolce & Gabbana;分类:fragrances;SKU:FRA-DOL-DOL-009;评分:3.96/5;折扣:0.62%;保修:3 year warranty;配送:Ships in 1 month;来源:DummyJSON products'),
(10, 12, 'Gucci Bloom Eau de', 'Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It''s a modern and romantic scent.', 79.99, 93.44, 91, 97, 1, 'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/1.webp', '<p>Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It''s a modern and romantic scent.</p><p>Brand: Gucci</p><p>Rating: 2.74/5</p><p>Tags: fragrances, perfumes</p>', '品牌:Gucci;分类:fragrances;SKU:FRA-GUC-GUC-010;评分:2.74/5;折扣:14.39%;保修:6 months warranty;配送:Ships overnight;来源:DummyJSON products'),
(11, 13, 'Annibale Colombo Bed', 'The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.', 1899.99, 2078.08, 88, 114, 1, 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/1.webp', '<p>The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.</p><p>Brand: Annibale Colombo</p><p>Rating: 4.77/5</p><p>Tags: furniture, beds</p>', '品牌:Annibale Colombo;分类:furniture;SKU:FUR-ANN-ANN-011;评分:4.77/5;折扣:8.57%;保修:1 year warranty;配送:Ships in 1 month;来源:DummyJSON products'),
(12, 13, 'Annibale Colombo Sofa', 'The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.', 2499.99, 2920.55, 60, 71, 1, 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/1.webp', '<p>The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.</p><p>Brand: Annibale Colombo</p><p>Rating: 3.92/5</p><p>Tags: furniture, sofas</p>', '品牌:Annibale Colombo;分类:furniture;SKU:FUR-ANN-ANN-012;评分:3.92/5;折扣:14.4%;保修:Lifetime warranty;配送:Ships in 1 week;来源:DummyJSON products'),
(13, 13, 'Bedside Table African Cherry', 'The Bedside Table in African Cherry is a stylish and functional addition to your bedroom, providing convenient storage space and a touch of elegance.', 299.99, 370.77, 64, 88, 1, 'https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/1.webp', '<p>The Bedside Table in African Cherry is a stylish and functional addition to your bedroom, providing convenient storage space and a touch of elegance.</p><p>Brand: Furniture Co.</p><p>Rating: 2.87/5</p><p>Tags: furniture, bedside tables</p>', '品牌:Furniture Co.;分类:furniture;SKU:FUR-FUR-BED-013;评分:2.87/5;折扣:19.09%;保修:5 year warranty;配送:Ships overnight;来源:DummyJSON products'),
(14, 13, 'Knoll Saarinen Executive Conference Chair', 'The Knoll Saarinen Executive Conference Chair is a modern and ergonomic chair, perfect for your office or conference room with its timeless design.', 499.99, 510.25, 26, 105, 1, 'https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/1.webp', '<p>The Knoll Saarinen Executive Conference Chair is a modern and ergonomic chair, perfect for your office or conference room with its timeless design.</p><p>Brand: Knoll</p><p>Rating: 4.88/5</p><p>Tags: furniture, office chairs</p>', '品牌:Knoll;分类:furniture;SKU:FUR-KNO-KNO-014;评分:4.88/5;折扣:2.01%;保修:2 year warranty;配送:Ships overnight;来源:DummyJSON products'),
(15, 13, 'Wooden Bathroom Sink With Mirror', 'The Wooden Bathroom Sink with Mirror is a unique and stylish addition to your bathroom, featuring a wooden sink countertop and a matching mirror.', 799.99, 877.18, 7, 122, 1, 'https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/1.webp', '<p>The Wooden Bathroom Sink with Mirror is a unique and stylish addition to your bathroom, featuring a wooden sink countertop and a matching mirror.</p><p>Brand: Bath Trends</p><p>Rating: 3.59/5</p><p>Tags: furniture, bathroom</p>', '品牌:Bath Trends;分类:furniture;SKU:FUR-BAT-WOO-015;评分:3.59/5;折扣:8.8%;保修:3 year warranty;配送:Ships in 3-5 business days;来源:DummyJSON products'),
(16, 14, 'Apple', 'Fresh and crisp apples, perfect for snacking or incorporating into various recipes.', 1.99, 2.28, 8, 79, 1, 'https://cdn.dummyjson.com/product-images/groceries/apple/1.webp', '<p>Fresh and crisp apples, perfect for snacking or incorporating into various recipes.</p><p>Brand: Generic</p><p>Rating: 4.19/5</p><p>Tags: fruits</p>', '分类:groceries;SKU:GRO-BRD-APP-016;评分:4.19/5;折扣:12.62%;保修:3 year warranty;配送:Ships in 2 weeks;来源:DummyJSON products'),
(17, 14, 'Beef Steak', 'High-quality beef steak, great for grilling or cooking to your preferred level of doneness.', 12.99, 14.37, 86, 96, 1, 'https://cdn.dummyjson.com/product-images/groceries/beef-steak/1.webp', '<p>High-quality beef steak, great for grilling or cooking to your preferred level of doneness.</p><p>Brand: Generic</p><p>Rating: 4.47/5</p><p>Tags: meat</p>', '分类:groceries;SKU:GRO-BRD-BEE-017;评分:4.47/5;折扣:9.61%;保修:3 year warranty;配送:Ships overnight;来源:DummyJSON products'),
(18, 14, 'Cat Food', 'Nutritious cat food formulated to meet the dietary needs of your feline friend.', 8.99, 9.94, 46, 113, 1, 'https://cdn.dummyjson.com/product-images/groceries/cat-food/1.webp', '<p>Nutritious cat food formulated to meet the dietary needs of your feline friend.</p><p>Brand: Generic</p><p>Rating: 3.13/5</p><p>Tags: pet supplies, cat food</p>', '分类:groceries;SKU:GRO-BRD-FOO-018;评分:3.13/5;折扣:9.58%;保修:1 year warranty;配送:Ships overnight;来源:DummyJSON products'),
(19, 14, 'Chicken Meat', 'Fresh and tender chicken meat, suitable for various culinary preparations.', 9.99, 11.58, 97, 70, 1, 'https://cdn.dummyjson.com/product-images/groceries/chicken-meat/1.webp', '<p>Fresh and tender chicken meat, suitable for various culinary preparations.</p><p>Brand: Generic</p><p>Rating: 3.19/5</p><p>Tags: meat</p>', '分类:groceries;SKU:GRO-BRD-CHI-019;评分:3.19/5;折扣:13.7%;保修:1 year warranty;配送:Ships in 1 month;来源:DummyJSON products'),
(20, 14, 'Cooking Oil', 'Versatile cooking oil suitable for frying, sautéing, and various culinary applications.', 4.99, 5.50, 10, 87, 1, 'https://cdn.dummyjson.com/product-images/groceries/cooking-oil/1.webp', '<p>Versatile cooking oil suitable for frying, sautéing, and various culinary applications.</p><p>Brand: Generic</p><p>Rating: 4.8/5</p><p>Tags: cooking essentials</p>', '分类:groceries;SKU:GRO-BRD-COO-020;评分:4.8/5;折扣:9.33%;保修:Lifetime warranty;配送:Ships in 1-2 business days;来源:DummyJSON products'),
(21, 14, 'Cucumber', 'Crisp and hydrating cucumbers, ideal for salads, snacks, or as a refreshing side.', 1.49, 1.49, 84, 104, 1, 'https://cdn.dummyjson.com/product-images/groceries/cucumber/1.webp', '<p>Crisp and hydrating cucumbers, ideal for salads, snacks, or as a refreshing side.</p><p>Brand: Generic</p><p>Rating: 4.07/5</p><p>Tags: vegetables</p>', '分类:groceries;SKU:GRO-BRD-CUC-021;评分:4.07/5;折扣:0.16%;保修:2 year warranty;配送:Ships in 1-2 business days;来源:DummyJSON products'),
(22, 14, 'Dog Food', 'Specially formulated dog food designed to provide essential nutrients for your canine companion.', 10.99, 12.25, 71, 121, 1, 'https://cdn.dummyjson.com/product-images/groceries/dog-food/1.webp', '<p>Specially formulated dog food designed to provide essential nutrients for your canine companion.</p><p>Brand: Generic</p><p>Rating: 4.55/5</p><p>Tags: pet supplies, dog food</p>', '分类:groceries;SKU:GRO-BRD-FOO-022;评分:4.55/5;折扣:10.27%;保修:No warranty;配送:Ships in 1-2 business days;来源:DummyJSON products'),
(23, 14, 'Eggs', 'Fresh eggs, a versatile ingredient for baking, cooking, or breakfast.', 2.99, 3.36, 9, 78, 1, 'https://cdn.dummyjson.com/product-images/groceries/eggs/1.webp', '<p>Fresh eggs, a versatile ingredient for baking, cooking, or breakfast.</p><p>Brand: Generic</p><p>Rating: 2.53/5</p><p>Tags: dairy</p>', '分类:groceries;SKU:GRO-BRD-EGG-023;评分:2.53/5;折扣:11.05%;保修:1 week warranty;配送:Ships in 1 week;来源:DummyJSON products'),
(24, 14, 'Fish Steak', 'Quality fish steak, suitable for grilling, baking, or pan-searing.', 14.99, 15.65, 74, 95, 1, 'https://cdn.dummyjson.com/product-images/groceries/fish-steak/1.webp', '<p>Quality fish steak, suitable for grilling, baking, or pan-searing.</p><p>Brand: Generic</p><p>Rating: 3.78/5</p><p>Tags: seafood</p>', '分类:groceries;SKU:GRO-BRD-FIS-024;评分:3.78/5;折扣:4.23%;保修:1 month warranty;配送:Ships in 3-5 business days;来源:DummyJSON products'),
(25, 14, 'Green Bell Pepper', 'Fresh and vibrant green bell pepper, perfect for adding color and flavor to your dishes.', 1.29, 1.29, 33, 112, 1, 'https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/1.webp', '<p>Fresh and vibrant green bell pepper, perfect for adding color and flavor to your dishes.</p><p>Brand: Generic</p><p>Rating: 3.25/5</p><p>Tags: vegetables</p>', '分类:groceries;SKU:GRO-BRD-GRE-025;评分:3.25/5;折扣:0.16%;保修:1 month warranty;配送:Ships in 1 week;来源:DummyJSON products'),
(26, 14, 'Green Chili Pepper', 'Spicy green chili pepper, ideal for adding heat to your favorite recipes.', 0.99, 1.00, 3, 69, 1, 'https://cdn.dummyjson.com/product-images/groceries/green-chili-pepper/1.webp', '<p>Spicy green chili pepper, ideal for adding heat to your favorite recipes.</p><p>Brand: Generic</p><p>Rating: 3.66/5</p><p>Tags: vegetables</p>', '分类:groceries;SKU:GRO-BRD-GRE-026;评分:3.66/5;折扣:1%;保修:2 year warranty;配送:Ships in 1 week;来源:DummyJSON products'),
(27, 14, 'Honey Jar', 'Pure and natural honey in a convenient jar, perfect for sweetening beverages or drizzling over food.', 6.99, 8.17, 34, 86, 1, 'https://cdn.dummyjson.com/product-images/groceries/honey-jar/1.webp', '<p>Pure and natural honey in a convenient jar, perfect for sweetening beverages or drizzling over food.</p><p>Brand: Generic</p><p>Rating: 3.97/5</p><p>Tags: condiments</p>', '分类:groceries;SKU:GRO-BRD-HON-027;评分:3.97/5;折扣:14.4%;保修:1 month warranty;配送:Ships in 1-2 business days;来源:DummyJSON products'),
(28, 14, 'Ice Cream', 'Creamy and delicious ice cream, available in various flavors for a delightful treat.', 5.49, 6.01, 27, 103, 1, 'https://cdn.dummyjson.com/product-images/groceries/ice-cream/1.webp', '<p>Creamy and delicious ice cream, available in various flavors for a delightful treat.</p><p>Brand: Generic</p><p>Rating: 3.39/5</p><p>Tags: desserts</p>', '分类:groceries;SKU:GRO-BRD-CRE-028;评分:3.39/5;折扣:8.69%;保修:1 month warranty;配送:Ships in 2 weeks;来源:DummyJSON products'),
(29, 14, 'Juice', 'Refreshing fruit juice, packed with vitamins and great for staying hydrated.', 3.99, 4.54, 50, 120, 1, 'https://cdn.dummyjson.com/product-images/groceries/juice/1.webp', '<p>Refreshing fruit juice, packed with vitamins and great for staying hydrated.</p><p>Brand: Generic</p><p>Rating: 3.94/5</p><p>Tags: beverages</p>', '分类:groceries;SKU:GRO-BRD-JUI-029;评分:3.94/5;折扣:12.06%;保修:6 months warranty;配送:Ships in 1 week;来源:DummyJSON products'),
(30, 14, 'Kiwi', 'Nutrient-rich kiwi, perfect for snacking or adding a tropical twist to your dishes.', 2.49, 2.94, 99, 77, 1, 'https://cdn.dummyjson.com/product-images/groceries/kiwi/1.webp', '<p>Nutrient-rich kiwi, perfect for snacking or adding a tropical twist to your dishes.</p><p>Brand: Generic</p><p>Rating: 4.93/5</p><p>Tags: fruits</p>', '分类:groceries;SKU:GRO-BRD-KIW-030;评分:4.93/5;折扣:15.22%;保修:6 months warranty;配送:Ships overnight;来源:DummyJSON products');

INSERT INTO product_image (product_id, url, sort_order) VALUES
(1, 'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp', 1),
(2, 'https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/1.webp', 1),
(3, 'https://cdn.dummyjson.com/product-images/beauty/powder-canister/1.webp', 1),
(4, 'https://cdn.dummyjson.com/product-images/beauty/red-lipstick/1.webp', 1),
(5, 'https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/1.webp', 1),
(6, 'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/1.webp', 1),
(6, 'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/2.webp', 2),
(6, 'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/3.webp', 3),
(7, 'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/1.webp', 1),
(7, 'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/2.webp', 2),
(7, 'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/3.webp', 3),
(8, 'https://cdn.dummyjson.com/product-images/fragrances/dior-j''adore/1.webp', 1),
(8, 'https://cdn.dummyjson.com/product-images/fragrances/dior-j''adore/2.webp', 2),
(8, 'https://cdn.dummyjson.com/product-images/fragrances/dior-j''adore/3.webp', 3),
(9, 'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/1.webp', 1),
(9, 'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/2.webp', 2),
(9, 'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/3.webp', 3),
(10, 'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/1.webp', 1),
(10, 'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/2.webp', 2),
(10, 'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/3.webp', 3),
(11, 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/1.webp', 1),
(11, 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/2.webp', 2),
(11, 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/3.webp', 3),
(12, 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/1.webp', 1),
(12, 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/2.webp', 2),
(12, 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/3.webp', 3),
(13, 'https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/1.webp', 1),
(13, 'https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/2.webp', 2),
(13, 'https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/3.webp', 3),
(14, 'https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/1.webp', 1),
(14, 'https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/2.webp', 2),
(14, 'https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/3.webp', 3),
(15, 'https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/1.webp', 1),
(15, 'https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/2.webp', 2),
(15, 'https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/3.webp', 3),
(16, 'https://cdn.dummyjson.com/product-images/groceries/apple/1.webp', 1),
(17, 'https://cdn.dummyjson.com/product-images/groceries/beef-steak/1.webp', 1),
(18, 'https://cdn.dummyjson.com/product-images/groceries/cat-food/1.webp', 1),
(19, 'https://cdn.dummyjson.com/product-images/groceries/chicken-meat/1.webp', 1),
(19, 'https://cdn.dummyjson.com/product-images/groceries/chicken-meat/2.webp', 2),
(20, 'https://cdn.dummyjson.com/product-images/groceries/cooking-oil/1.webp', 1),
(21, 'https://cdn.dummyjson.com/product-images/groceries/cucumber/1.webp', 1),
(22, 'https://cdn.dummyjson.com/product-images/groceries/dog-food/1.webp', 1),
(23, 'https://cdn.dummyjson.com/product-images/groceries/eggs/1.webp', 1),
(24, 'https://cdn.dummyjson.com/product-images/groceries/fish-steak/1.webp', 1),
(25, 'https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/1.webp', 1),
(26, 'https://cdn.dummyjson.com/product-images/groceries/green-chili-pepper/1.webp', 1),
(27, 'https://cdn.dummyjson.com/product-images/groceries/honey-jar/1.webp', 1),
(28, 'https://cdn.dummyjson.com/product-images/groceries/ice-cream/1.webp', 1),
(28, 'https://cdn.dummyjson.com/product-images/groceries/ice-cream/2.webp', 2),
(28, 'https://cdn.dummyjson.com/product-images/groceries/ice-cream/3.webp', 3),
(28, 'https://cdn.dummyjson.com/product-images/groceries/ice-cream/4.webp', 4),
(29, 'https://cdn.dummyjson.com/product-images/groceries/juice/1.webp', 1),
(30, 'https://cdn.dummyjson.com/product-images/groceries/kiwi/1.webp', 1);

INSERT INTO product_sku (product_id, sku_code, color, size, price, stock, image) VALUES
(1, 'BEA-ESS-ESS-001-V01', NULL, 'Standard', 9.49, 33, 'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp'),
(1, 'BEA-ESS-ESS-001-V02', NULL, 'Mini', 9.99, 33, 'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp'),
(1, 'BEA-ESS-ESS-001-V03', 'Limited', 'Gift Set', 10.79, 33, 'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp'),
(2, 'BEA-GLA-EYE-002-V01', NULL, 'Standard', 18.99, 11, 'https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/1.webp'),
(2, 'BEA-GLA-EYE-002-V02', NULL, 'Mini', 19.99, 11, 'https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/1.webp'),
(2, 'BEA-GLA-EYE-002-V03', 'Limited', 'Gift Set', 21.59, 11, 'https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/1.webp'),
(3, 'BEA-VEL-POW-003-V01', NULL, 'Standard', 14.24, 29, 'https://cdn.dummyjson.com/product-images/beauty/powder-canister/1.webp'),
(3, 'BEA-VEL-POW-003-V02', NULL, 'Mini', 14.99, 29, 'https://cdn.dummyjson.com/product-images/beauty/powder-canister/1.webp'),
(3, 'BEA-VEL-POW-003-V03', 'Limited', 'Gift Set', 16.19, 29, 'https://cdn.dummyjson.com/product-images/beauty/powder-canister/1.webp'),
(4, 'BEA-CHI-LIP-004-V01', NULL, 'Standard', 12.34, 30, 'https://cdn.dummyjson.com/product-images/beauty/red-lipstick/1.webp'),
(4, 'BEA-CHI-LIP-004-V02', NULL, 'Mini', 12.99, 30, 'https://cdn.dummyjson.com/product-images/beauty/red-lipstick/1.webp'),
(4, 'BEA-CHI-LIP-004-V03', 'Limited', 'Gift Set', 14.03, 30, 'https://cdn.dummyjson.com/product-images/beauty/red-lipstick/1.webp'),
(5, 'BEA-NAI-NAI-005-V01', NULL, 'Standard', 8.54, 26, 'https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/1.webp'),
(5, 'BEA-NAI-NAI-005-V02', NULL, 'Mini', 8.99, 26, 'https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/1.webp'),
(5, 'BEA-NAI-NAI-005-V03', 'Limited', 'Gift Set', 9.71, 26, 'https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/1.webp'),
(6, 'FRA-CAL-CAL-006-V01', NULL, '30ml', 47.49, 9, 'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/1.webp'),
(6, 'FRA-CAL-CAL-006-V02', NULL, '50ml', 49.99, 9, 'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/1.webp'),
(6, 'FRA-CAL-CAL-006-V03', 'Limited', '100ml', 53.99, 9, 'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/1.webp'),
(7, 'FRA-CHA-CHA-007-V01', NULL, '30ml', 123.49, 19, 'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/1.webp'),
(7, 'FRA-CHA-CHA-007-V02', NULL, '50ml', 129.99, 19, 'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/1.webp'),
(7, 'FRA-CHA-CHA-007-V03', 'Limited', '100ml', 140.39, 19, 'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/1.webp'),
(8, 'FRA-DIO-DIO-008-V01', NULL, '30ml', 85.49, 32, 'https://cdn.dummyjson.com/product-images/fragrances/dior-j''adore/1.webp'),
(8, 'FRA-DIO-DIO-008-V02', NULL, '50ml', 89.99, 32, 'https://cdn.dummyjson.com/product-images/fragrances/dior-j''adore/1.webp'),
(8, 'FRA-DIO-DIO-008-V03', 'Limited', '100ml', 97.19, 32, 'https://cdn.dummyjson.com/product-images/fragrances/dior-j''adore/1.webp'),
(9, 'FRA-DOL-DOL-009-V01', NULL, '30ml', 66.49, 1, 'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/1.webp'),
(9, 'FRA-DOL-DOL-009-V02', NULL, '50ml', 69.99, 1, 'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/1.webp'),
(9, 'FRA-DOL-DOL-009-V03', 'Limited', '100ml', 75.59, 1, 'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/1.webp'),
(10, 'FRA-GUC-GUC-010-V01', NULL, '30ml', 75.99, 30, 'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/1.webp'),
(10, 'FRA-GUC-GUC-010-V02', NULL, '50ml', 79.99, 30, 'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/1.webp'),
(10, 'FRA-GUC-GUC-010-V03', 'Limited', '100ml', 86.39, 30, 'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/1.webp'),
(11, 'FUR-ANN-ANN-011-V01', NULL, 'Standard', 1804.99, 29, 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/1.webp'),
(11, 'FUR-ANN-ANN-011-V02', NULL, 'Large', 1899.99, 29, 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/1.webp'),
(11, 'FUR-ANN-ANN-011-V03', 'Limited', 'Family Pack', 2051.99, 29, 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/1.webp'),
(12, 'FUR-ANN-ANN-012-V01', NULL, 'Standard', 2374.99, 20, 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/1.webp'),
(12, 'FUR-ANN-ANN-012-V02', NULL, 'Large', 2499.99, 20, 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/1.webp'),
(12, 'FUR-ANN-ANN-012-V03', 'Limited', 'Family Pack', 2699.99, 20, 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/1.webp'),
(13, 'FUR-FUR-BED-013-V01', NULL, 'Standard', 284.99, 21, 'https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/1.webp'),
(13, 'FUR-FUR-BED-013-V02', NULL, 'Large', 299.99, 21, 'https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/1.webp'),
(13, 'FUR-FUR-BED-013-V03', 'Limited', 'Family Pack', 323.99, 21, 'https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/1.webp'),
(14, 'FUR-KNO-KNO-014-V01', NULL, 'Standard', 474.99, 8, 'https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/1.webp'),
(14, 'FUR-KNO-KNO-014-V02', NULL, 'Large', 499.99, 8, 'https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/1.webp'),
(14, 'FUR-KNO-KNO-014-V03', 'Limited', 'Family Pack', 539.99, 8, 'https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/1.webp'),
(15, 'FUR-BAT-WOO-015-V01', NULL, 'Standard', 759.99, 2, 'https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/1.webp'),
(15, 'FUR-BAT-WOO-015-V02', NULL, 'Large', 799.99, 2, 'https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/1.webp'),
(15, 'FUR-BAT-WOO-015-V03', 'Limited', 'Family Pack', 863.99, 2, 'https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/1.webp'),
(16, 'GRO-BRD-APP-016-V01', NULL, 'Standard', 1.89, 2, 'https://cdn.dummyjson.com/product-images/groceries/apple/1.webp'),
(16, 'GRO-BRD-APP-016-V02', NULL, 'Large', 1.99, 2, 'https://cdn.dummyjson.com/product-images/groceries/apple/1.webp'),
(16, 'GRO-BRD-APP-016-V03', 'Limited', 'Family Pack', 2.15, 2, 'https://cdn.dummyjson.com/product-images/groceries/apple/1.webp'),
(17, 'GRO-BRD-BEE-017-V01', NULL, 'Standard', 12.34, 28, 'https://cdn.dummyjson.com/product-images/groceries/beef-steak/1.webp'),
(17, 'GRO-BRD-BEE-017-V02', NULL, 'Large', 12.99, 28, 'https://cdn.dummyjson.com/product-images/groceries/beef-steak/1.webp'),
(17, 'GRO-BRD-BEE-017-V03', 'Limited', 'Family Pack', 14.03, 28, 'https://cdn.dummyjson.com/product-images/groceries/beef-steak/1.webp'),
(18, 'GRO-BRD-FOO-018-V01', NULL, 'Standard', 8.54, 15, 'https://cdn.dummyjson.com/product-images/groceries/cat-food/1.webp'),
(18, 'GRO-BRD-FOO-018-V02', NULL, 'Large', 8.99, 15, 'https://cdn.dummyjson.com/product-images/groceries/cat-food/1.webp'),
(18, 'GRO-BRD-FOO-018-V03', 'Limited', 'Family Pack', 9.71, 15, 'https://cdn.dummyjson.com/product-images/groceries/cat-food/1.webp'),
(19, 'GRO-BRD-CHI-019-V01', NULL, 'Standard', 9.49, 32, 'https://cdn.dummyjson.com/product-images/groceries/chicken-meat/1.webp'),
(19, 'GRO-BRD-CHI-019-V02', NULL, 'Large', 9.99, 32, 'https://cdn.dummyjson.com/product-images/groceries/chicken-meat/1.webp'),
(19, 'GRO-BRD-CHI-019-V03', 'Limited', 'Family Pack', 10.79, 32, 'https://cdn.dummyjson.com/product-images/groceries/chicken-meat/1.webp'),
(20, 'GRO-BRD-COO-020-V01', NULL, 'Standard', 4.74, 3, 'https://cdn.dummyjson.com/product-images/groceries/cooking-oil/1.webp'),
(20, 'GRO-BRD-COO-020-V02', NULL, 'Large', 4.99, 3, 'https://cdn.dummyjson.com/product-images/groceries/cooking-oil/1.webp'),
(20, 'GRO-BRD-COO-020-V03', 'Limited', 'Family Pack', 5.39, 3, 'https://cdn.dummyjson.com/product-images/groceries/cooking-oil/1.webp'),
(21, 'GRO-BRD-CUC-021-V01', NULL, 'Standard', 1.42, 28, 'https://cdn.dummyjson.com/product-images/groceries/cucumber/1.webp'),
(21, 'GRO-BRD-CUC-021-V02', NULL, 'Large', 1.49, 28, 'https://cdn.dummyjson.com/product-images/groceries/cucumber/1.webp'),
(21, 'GRO-BRD-CUC-021-V03', 'Limited', 'Family Pack', 1.61, 28, 'https://cdn.dummyjson.com/product-images/groceries/cucumber/1.webp'),
(22, 'GRO-BRD-FOO-022-V01', NULL, 'Standard', 10.44, 23, 'https://cdn.dummyjson.com/product-images/groceries/dog-food/1.webp'),
(22, 'GRO-BRD-FOO-022-V02', NULL, 'Large', 10.99, 23, 'https://cdn.dummyjson.com/product-images/groceries/dog-food/1.webp'),
(22, 'GRO-BRD-FOO-022-V03', 'Limited', 'Family Pack', 11.87, 23, 'https://cdn.dummyjson.com/product-images/groceries/dog-food/1.webp'),
(23, 'GRO-BRD-EGG-023-V01', NULL, 'Standard', 2.84, 3, 'https://cdn.dummyjson.com/product-images/groceries/eggs/1.webp'),
(23, 'GRO-BRD-EGG-023-V02', NULL, 'Large', 2.99, 3, 'https://cdn.dummyjson.com/product-images/groceries/eggs/1.webp'),
(23, 'GRO-BRD-EGG-023-V03', 'Limited', 'Family Pack', 3.23, 3, 'https://cdn.dummyjson.com/product-images/groceries/eggs/1.webp'),
(24, 'GRO-BRD-FIS-024-V01', NULL, 'Standard', 14.24, 24, 'https://cdn.dummyjson.com/product-images/groceries/fish-steak/1.webp'),
(24, 'GRO-BRD-FIS-024-V02', NULL, 'Large', 14.99, 24, 'https://cdn.dummyjson.com/product-images/groceries/fish-steak/1.webp'),
(24, 'GRO-BRD-FIS-024-V03', 'Limited', 'Family Pack', 16.19, 24, 'https://cdn.dummyjson.com/product-images/groceries/fish-steak/1.webp'),
(25, 'GRO-BRD-GRE-025-V01', NULL, 'Standard', 1.23, 11, 'https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/1.webp'),
(25, 'GRO-BRD-GRE-025-V02', NULL, 'Large', 1.29, 11, 'https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/1.webp'),
(25, 'GRO-BRD-GRE-025-V03', 'Limited', 'Family Pack', 1.39, 11, 'https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/1.webp'),
(26, 'GRO-BRD-GRE-026-V01', NULL, 'Standard', 0.94, 1, 'https://cdn.dummyjson.com/product-images/groceries/green-chili-pepper/1.webp'),
(26, 'GRO-BRD-GRE-026-V02', NULL, 'Large', 0.99, 1, 'https://cdn.dummyjson.com/product-images/groceries/green-chili-pepper/1.webp'),
(26, 'GRO-BRD-GRE-026-V03', 'Limited', 'Family Pack', 1.07, 1, 'https://cdn.dummyjson.com/product-images/groceries/green-chili-pepper/1.webp'),
(27, 'GRO-BRD-HON-027-V01', NULL, 'Standard', 6.64, 11, 'https://cdn.dummyjson.com/product-images/groceries/honey-jar/1.webp'),
(27, 'GRO-BRD-HON-027-V02', NULL, 'Large', 6.99, 11, 'https://cdn.dummyjson.com/product-images/groceries/honey-jar/1.webp'),
(27, 'GRO-BRD-HON-027-V03', 'Limited', 'Family Pack', 7.55, 11, 'https://cdn.dummyjson.com/product-images/groceries/honey-jar/1.webp'),
(28, 'GRO-BRD-CRE-028-V01', NULL, 'Standard', 5.22, 9, 'https://cdn.dummyjson.com/product-images/groceries/ice-cream/1.webp'),
(28, 'GRO-BRD-CRE-028-V02', NULL, 'Large', 5.49, 9, 'https://cdn.dummyjson.com/product-images/groceries/ice-cream/1.webp'),
(28, 'GRO-BRD-CRE-028-V03', 'Limited', 'Family Pack', 5.93, 9, 'https://cdn.dummyjson.com/product-images/groceries/ice-cream/1.webp'),
(29, 'GRO-BRD-JUI-029-V01', NULL, 'Standard', 3.79, 16, 'https://cdn.dummyjson.com/product-images/groceries/juice/1.webp'),
(29, 'GRO-BRD-JUI-029-V02', NULL, 'Large', 3.99, 16, 'https://cdn.dummyjson.com/product-images/groceries/juice/1.webp'),
(29, 'GRO-BRD-JUI-029-V03', 'Limited', 'Family Pack', 4.31, 16, 'https://cdn.dummyjson.com/product-images/groceries/juice/1.webp'),
(30, 'GRO-BRD-KIW-030-V01', NULL, 'Standard', 2.37, 33, 'https://cdn.dummyjson.com/product-images/groceries/kiwi/1.webp'),
(30, 'GRO-BRD-KIW-030-V02', NULL, 'Large', 2.49, 33, 'https://cdn.dummyjson.com/product-images/groceries/kiwi/1.webp'),
(30, 'GRO-BRD-KIW-030-V03', 'Limited', 'Family Pack', 2.69, 33, 'https://cdn.dummyjson.com/product-images/groceries/kiwi/1.webp');

INSERT INTO product_spec (product_id, spec_name, spec_value) VALUES
(1, '品牌', 'Essence'),
(1, 'DummyJSON 分类', 'beauty'),
(1, 'SKU', 'BEA-ESS-ESS-001'),
(1, '评分', '2.56/5'),
(1, '折扣', '10.48%'),
(1, '保修', '1 week warranty'),
(1, '配送', 'Ships in 3-5 business days'),
(1, '标签', 'beauty, mascara'),
(2, '品牌', 'Glamour Beauty'),
(2, 'DummyJSON 分类', 'beauty'),
(2, 'SKU', 'BEA-GLA-EYE-002'),
(2, '评分', '2.86/5'),
(2, '折扣', '18.19%'),
(2, '保修', '1 year warranty'),
(2, '配送', 'Ships in 2 weeks'),
(2, '标签', 'beauty, eyeshadow'),
(3, '品牌', 'Velvet Touch'),
(3, 'DummyJSON 分类', 'beauty'),
(3, 'SKU', 'BEA-VEL-POW-003'),
(3, '评分', '4.64/5'),
(3, '折扣', '9.84%'),
(3, '保修', '3 months warranty'),
(3, '配送', 'Ships in 1-2 business days'),
(3, '标签', 'beauty, face powder'),
(4, '品牌', 'Chic Cosmetics'),
(4, 'DummyJSON 分类', 'beauty'),
(4, 'SKU', 'BEA-CHI-LIP-004'),
(4, '评分', '4.36/5'),
(4, '折扣', '12.16%'),
(4, '保修', '3 year warranty'),
(4, '配送', 'Ships in 1 week'),
(4, '标签', 'beauty, lipstick'),
(5, '品牌', 'Nail Couture'),
(5, 'DummyJSON 分类', 'beauty'),
(5, 'SKU', 'BEA-NAI-NAI-005'),
(5, '评分', '4.32/5'),
(5, '折扣', '11.44%'),
(5, '保修', '1 month warranty'),
(5, '配送', 'Ships overnight'),
(5, '标签', 'beauty, nail polish'),
(6, '品牌', 'Calvin Klein'),
(6, 'DummyJSON 分类', 'fragrances'),
(6, 'SKU', 'FRA-CAL-CAL-006'),
(6, '评分', '4.37/5'),
(6, '折扣', '1.89%'),
(6, '保修', '1 week warranty'),
(6, '配送', 'Ships overnight'),
(6, '标签', 'fragrances, perfumes'),
(7, '品牌', 'Chanel'),
(7, 'DummyJSON 分类', 'fragrances'),
(7, 'SKU', 'FRA-CHA-CHA-007'),
(7, '评分', '4.26/5'),
(7, '折扣', '16.51%'),
(7, '保修', '3 year warranty'),
(7, '配送', 'Ships overnight'),
(7, '标签', 'fragrances, perfumes'),
(8, '品牌', 'Dior'),
(8, 'DummyJSON 分类', 'fragrances'),
(8, 'SKU', 'FRA-DIO-DIO-008'),
(8, '评分', '3.8/5'),
(8, '折扣', '14.72%'),
(8, '保修', '1 week warranty'),
(8, '配送', 'Ships in 2 weeks'),
(8, '标签', 'fragrances, perfumes'),
(9, '品牌', 'Dolce & Gabbana'),
(9, 'DummyJSON 分类', 'fragrances'),
(9, 'SKU', 'FRA-DOL-DOL-009'),
(9, '评分', '3.96/5'),
(9, '折扣', '0.62%'),
(9, '保修', '3 year warranty'),
(9, '配送', 'Ships in 1 month'),
(9, '标签', 'fragrances, perfumes'),
(10, '品牌', 'Gucci'),
(10, 'DummyJSON 分类', 'fragrances'),
(10, 'SKU', 'FRA-GUC-GUC-010'),
(10, '评分', '2.74/5'),
(10, '折扣', '14.39%'),
(10, '保修', '6 months warranty'),
(10, '配送', 'Ships overnight'),
(10, '标签', 'fragrances, perfumes'),
(11, '品牌', 'Annibale Colombo'),
(11, 'DummyJSON 分类', 'furniture'),
(11, 'SKU', 'FUR-ANN-ANN-011'),
(11, '评分', '4.77/5'),
(11, '折扣', '8.57%'),
(11, '保修', '1 year warranty'),
(11, '配送', 'Ships in 1 month'),
(11, '标签', 'furniture, beds'),
(12, '品牌', 'Annibale Colombo'),
(12, 'DummyJSON 分类', 'furniture'),
(12, 'SKU', 'FUR-ANN-ANN-012'),
(12, '评分', '3.92/5'),
(12, '折扣', '14.4%'),
(12, '保修', 'Lifetime warranty'),
(12, '配送', 'Ships in 1 week'),
(12, '标签', 'furniture, sofas'),
(13, '品牌', 'Furniture Co.'),
(13, 'DummyJSON 分类', 'furniture'),
(13, 'SKU', 'FUR-FUR-BED-013'),
(13, '评分', '2.87/5'),
(13, '折扣', '19.09%'),
(13, '保修', '5 year warranty'),
(13, '配送', 'Ships overnight'),
(13, '标签', 'furniture, bedside tables'),
(14, '品牌', 'Knoll'),
(14, 'DummyJSON 分类', 'furniture'),
(14, 'SKU', 'FUR-KNO-KNO-014'),
(14, '评分', '4.88/5'),
(14, '折扣', '2.01%'),
(14, '保修', '2 year warranty'),
(14, '配送', 'Ships overnight'),
(14, '标签', 'furniture, office chairs'),
(15, '品牌', 'Bath Trends'),
(15, 'DummyJSON 分类', 'furniture'),
(15, 'SKU', 'FUR-BAT-WOO-015'),
(15, '评分', '3.59/5'),
(15, '折扣', '8.8%'),
(15, '保修', '3 year warranty'),
(15, '配送', 'Ships in 3-5 business days'),
(15, '标签', 'furniture, bathroom'),
(16, '品牌', 'Generic'),
(16, 'DummyJSON 分类', 'groceries'),
(16, 'SKU', 'GRO-BRD-APP-016'),
(16, '评分', '4.19/5'),
(16, '折扣', '12.62%'),
(16, '保修', '3 year warranty'),
(16, '配送', 'Ships in 2 weeks'),
(16, '标签', 'fruits'),
(17, '品牌', 'Generic'),
(17, 'DummyJSON 分类', 'groceries'),
(17, 'SKU', 'GRO-BRD-BEE-017'),
(17, '评分', '4.47/5'),
(17, '折扣', '9.61%'),
(17, '保修', '3 year warranty'),
(17, '配送', 'Ships overnight'),
(17, '标签', 'meat'),
(18, '品牌', 'Generic'),
(18, 'DummyJSON 分类', 'groceries'),
(18, 'SKU', 'GRO-BRD-FOO-018'),
(18, '评分', '3.13/5'),
(18, '折扣', '9.58%'),
(18, '保修', '1 year warranty'),
(18, '配送', 'Ships overnight'),
(18, '标签', 'pet supplies, cat food'),
(19, '品牌', 'Generic'),
(19, 'DummyJSON 分类', 'groceries'),
(19, 'SKU', 'GRO-BRD-CHI-019'),
(19, '评分', '3.19/5'),
(19, '折扣', '13.7%'),
(19, '保修', '1 year warranty'),
(19, '配送', 'Ships in 1 month'),
(19, '标签', 'meat'),
(20, '品牌', 'Generic'),
(20, 'DummyJSON 分类', 'groceries'),
(20, 'SKU', 'GRO-BRD-COO-020'),
(20, '评分', '4.8/5'),
(20, '折扣', '9.33%'),
(20, '保修', 'Lifetime warranty'),
(20, '配送', 'Ships in 1-2 business days'),
(20, '标签', 'cooking essentials'),
(21, '品牌', 'Generic'),
(21, 'DummyJSON 分类', 'groceries'),
(21, 'SKU', 'GRO-BRD-CUC-021'),
(21, '评分', '4.07/5'),
(21, '折扣', '0.16%'),
(21, '保修', '2 year warranty'),
(21, '配送', 'Ships in 1-2 business days'),
(21, '标签', 'vegetables'),
(22, '品牌', 'Generic'),
(22, 'DummyJSON 分类', 'groceries'),
(22, 'SKU', 'GRO-BRD-FOO-022'),
(22, '评分', '4.55/5'),
(22, '折扣', '10.27%'),
(22, '保修', 'No warranty'),
(22, '配送', 'Ships in 1-2 business days'),
(22, '标签', 'pet supplies, dog food'),
(23, '品牌', 'Generic'),
(23, 'DummyJSON 分类', 'groceries'),
(23, 'SKU', 'GRO-BRD-EGG-023'),
(23, '评分', '2.53/5'),
(23, '折扣', '11.05%'),
(23, '保修', '1 week warranty'),
(23, '配送', 'Ships in 1 week'),
(23, '标签', 'dairy'),
(24, '品牌', 'Generic'),
(24, 'DummyJSON 分类', 'groceries'),
(24, 'SKU', 'GRO-BRD-FIS-024'),
(24, '评分', '3.78/5'),
(24, '折扣', '4.23%'),
(24, '保修', '1 month warranty'),
(24, '配送', 'Ships in 3-5 business days'),
(24, '标签', 'seafood'),
(25, '品牌', 'Generic'),
(25, 'DummyJSON 分类', 'groceries'),
(25, 'SKU', 'GRO-BRD-GRE-025'),
(25, '评分', '3.25/5'),
(25, '折扣', '0.16%'),
(25, '保修', '1 month warranty'),
(25, '配送', 'Ships in 1 week'),
(25, '标签', 'vegetables'),
(26, '品牌', 'Generic'),
(26, 'DummyJSON 分类', 'groceries'),
(26, 'SKU', 'GRO-BRD-GRE-026'),
(26, '评分', '3.66/5'),
(26, '折扣', '1%'),
(26, '保修', '2 year warranty'),
(26, '配送', 'Ships in 1 week'),
(26, '标签', 'vegetables'),
(27, '品牌', 'Generic'),
(27, 'DummyJSON 分类', 'groceries'),
(27, 'SKU', 'GRO-BRD-HON-027'),
(27, '评分', '3.97/5'),
(27, '折扣', '14.4%'),
(27, '保修', '1 month warranty'),
(27, '配送', 'Ships in 1-2 business days'),
(27, '标签', 'condiments'),
(28, '品牌', 'Generic'),
(28, 'DummyJSON 分类', 'groceries'),
(28, 'SKU', 'GRO-BRD-CRE-028'),
(28, '评分', '3.39/5'),
(28, '折扣', '8.69%'),
(28, '保修', '1 month warranty'),
(28, '配送', 'Ships in 2 weeks'),
(28, '标签', 'desserts'),
(29, '品牌', 'Generic'),
(29, 'DummyJSON 分类', 'groceries'),
(29, 'SKU', 'GRO-BRD-JUI-029'),
(29, '评分', '3.94/5'),
(29, '折扣', '12.06%'),
(29, '保修', '6 months warranty'),
(29, '配送', 'Ships in 1 week'),
(29, '标签', 'beverages'),
(30, '品牌', 'Generic'),
(30, 'DummyJSON 分类', 'groceries'),
(30, 'SKU', 'GRO-BRD-KIW-030'),
(30, '评分', '4.93/5'),
(30, '折扣', '15.22%'),
(30, '保修', '6 months warranty'),
(30, '配送', 'Ships overnight'),
(30, '标签', 'fruits');

INSERT INTO product_review (user_id, product_id, rating, content, image_url, created_at) VALUES
(1, 1, 3, 'Eleanor Collins: Would not recommend!', '', NOW() - INTERVAL 0 DAY),
(1, 1, 4, 'Lucas Gordon: Very satisfied!', '', NOW() - INTERVAL 1 DAY),
(1, 2, 5, 'Savannah Gomez: Great product!', '', NOW() - INTERVAL 0 DAY),
(1, 2, 4, 'Christian Perez: Awesome product!', '', NOW() - INTERVAL 1 DAY),
(1, 3, 4, 'Alexander Jones: Would buy again!', '', NOW() - INTERVAL 0 DAY),
(1, 3, 5, 'Elijah Cruz: Highly impressed!', '', NOW() - INTERVAL 1 DAY),
(1, 4, 4, 'Liam Garcia: Great product!', '', NOW() - INTERVAL 0 DAY),
(1, 4, 5, 'Ruby Andrews: Great product!', '', NOW() - INTERVAL 1 DAY),
(1, 5, 2, 'Benjamin Wilson: Poor quality!', '', NOW() - INTERVAL 0 DAY),
(1, 5, 5, 'Liam Smith: Great product!', '', NOW() - INTERVAL 1 DAY),
(1, 6, 2, 'Layla Young: Very disappointed!', '', NOW() - INTERVAL 0 DAY),
(1, 6, 4, 'Daniel Cook: Fast shipping!', '', NOW() - INTERVAL 1 DAY),
(1, 7, 4, 'Ruby Andrews: Highly impressed!', '', NOW() - INTERVAL 0 DAY),
(1, 7, 5, 'Leah Henderson: Awesome product!', '', NOW() - INTERVAL 1 DAY),
(1, 8, 5, 'Nicholas Bailey: Great value for money!', '', NOW() - INTERVAL 0 DAY),
(1, 8, 4, 'Penelope Harper: Great value for money!', '', NOW() - INTERVAL 1 DAY),
(1, 9, 4, 'Mateo Bennett: Would buy again!', '', NOW() - INTERVAL 0 DAY),
(1, 9, 4, 'Nolan Gonzalez: Highly recommended!', '', NOW() - INTERVAL 1 DAY),
(1, 10, 1, 'Cameron Perez: Very dissatisfied!', '', NOW() - INTERVAL 0 DAY),
(1, 10, 5, 'Daniel Cook: Very happy with my purchase!', '', NOW() - INTERVAL 1 DAY),
(1, 11, 2, 'Christopher West: Would not recommend!', '', NOW() - INTERVAL 0 DAY),
(1, 11, 4, 'Vivian Carter: Highly impressed!', '', NOW() - INTERVAL 1 DAY),
(1, 12, 3, 'Christian Perez: Very unhappy with my purchase!', '', NOW() - INTERVAL 0 DAY),
(1, 12, 5, 'Lillian Bishop: Fast shipping!', '', NOW() - INTERVAL 1 DAY),
(1, 13, 4, 'Aaliyah Hanson: Excellent quality!', '', NOW() - INTERVAL 0 DAY),
(1, 13, 4, 'Liam Smith: Excellent quality!', '', NOW() - INTERVAL 1 DAY),
(1, 14, 2, 'Ella Cook: Waste of money!', '', NOW() - INTERVAL 0 DAY),
(1, 14, 2, 'Clara Berry: Very dissatisfied!', '', NOW() - INTERVAL 1 DAY),
(1, 15, 4, 'Logan Torres: Fast shipping!', '', NOW() - INTERVAL 0 DAY),
(1, 15, 5, 'Aria Parker: Very pleased!', '', NOW() - INTERVAL 1 DAY),
(1, 16, 5, 'Sophia Brown: Very satisfied!', '', NOW() - INTERVAL 0 DAY),
(1, 16, 1, 'Scarlett Bowman: Very dissatisfied!', '', NOW() - INTERVAL 1 DAY),
(1, 17, 3, 'Eleanor Tyler: Would not recommend!', '', NOW() - INTERVAL 0 DAY),
(1, 17, 4, 'Alexander Jones: Fast shipping!', '', NOW() - INTERVAL 1 DAY),
(1, 18, 3, 'Noah Lewis: Would not recommend!', '', NOW() - INTERVAL 0 DAY),
(1, 18, 3, 'Ruby Andrews: Very unhappy with my purchase!', '', NOW() - INTERVAL 1 DAY),
(1, 19, 5, 'Mateo Bennett: Great product!', '', NOW() - INTERVAL 0 DAY),
(1, 19, 4, 'Jackson Evans: Highly recommended!', '', NOW() - INTERVAL 1 DAY),
(1, 20, 5, 'Victoria McDonald: Very happy with my purchase!', '', NOW() - INTERVAL 0 DAY),
(1, 20, 2, 'Hazel Evans: Would not recommend!', '', NOW() - INTERVAL 1 DAY),
(1, 21, 4, 'Lincoln Kelly: Great product!', '', NOW() - INTERVAL 0 DAY),
(1, 21, 4, 'Savannah Gomez: Great value for money!', '', NOW() - INTERVAL 1 DAY),
(1, 22, 5, 'Nicholas Edwards: Excellent quality!', '', NOW() - INTERVAL 0 DAY),
(1, 22, 5, 'Zachary Lee: Awesome product!', '', NOW() - INTERVAL 1 DAY),
(1, 23, 3, 'Penelope King: Disappointing product!', '', NOW() - INTERVAL 0 DAY),
(1, 23, 3, 'Eleanor Tyler: Poor quality!', '', NOW() - INTERVAL 1 DAY),
(1, 24, 2, 'Caleb Perkins: Would not buy again!', '', NOW() - INTERVAL 0 DAY),
(1, 24, 5, 'Isabella Jackson: Excellent quality!', '', NOW() - INTERVAL 1 DAY),
(1, 25, 4, 'Avery Carter: Highly recommended!', '', NOW() - INTERVAL 0 DAY),
(1, 25, 3, 'Henry Hill: Would not recommend!', '', NOW() - INTERVAL 1 DAY),
(1, 26, 4, 'Luna Russell: Great product!', '', NOW() - INTERVAL 0 DAY),
(1, 26, 1, 'Noah Lewis: Waste of money!', '', NOW() - INTERVAL 1 DAY),
(1, 27, 1, 'Autumn Gomez: Very disappointed!', '', NOW() - INTERVAL 0 DAY),
(1, 27, 4, 'Benjamin Wilson: Highly impressed!', '', NOW() - INTERVAL 1 DAY),
(1, 28, 5, 'Elijah Cruz: Very pleased!', '', NOW() - INTERVAL 0 DAY),
(1, 28, 4, 'Jace Smith: Excellent quality!', '', NOW() - INTERVAL 1 DAY),
(1, 29, 5, 'Nolan Gonzalez: Excellent quality!', '', NOW() - INTERVAL 0 DAY),
(1, 29, 4, 'Bella Grant: Would buy again!', '', NOW() - INTERVAL 1 DAY),
(1, 30, 4, 'Emily Brown: Highly recommended!', '', NOW() - INTERVAL 0 DAY),
(1, 30, 2, 'Jackson Morales: Would not buy again!', '', NOW() - INTERVAL 1 DAY);

INSERT INTO product_favorite (user_id, product_id) VALUES
(1, 1),
(1, 2),
(1, 3),
(1, 4);
