events {}
http {
  server {
    listen 80;
    location /api/auth/ { proxy_pass http://auth-service:8081; }
    location /api/admin/users { proxy_pass http://auth-service:8081; }
    location /api/products { proxy_pass http://product-service:8082; }
    location /api/categories { proxy_pass http://product-service:8082; }
    location /api/marketing { proxy_pass http://product-service:8082; }
    location /api/home { proxy_pass http://product-service:8082; }
    location /api/announcements { proxy_pass http://product-service:8082; }
    location /api/activity-notices { proxy_pass http://product-service:8082; }
    location /api/reviews { proxy_pass http://product-service:8082; }
    location /api/admin/activity-notices { proxy_pass http://product-service:8082; }
    location /api/orders { proxy_pass http://order-service:8083; }
    location /api/admin/orders { proxy_pass http://order-service:8083; }
    location /api/cart { proxy_pass http://order-service:8083; }
    location /api/addresses { proxy_pass http://order-service:8083; }
    location /api/consultations { proxy_pass http://order-service:8083; }
    location /api/admin/consultations { proxy_pass http://order-service:8083; }
  }
}
