FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY docker/maven/settings.xml /root/.m2/settings.xml
COPY backend/product-service/pom.xml ./
RUN mvn dependency:go-offline -B
COPY backend/product-service/src ./src
RUN mvn package -B -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 18092
ENTRYPOINT ["java","-jar","app.jar"]
